//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabel_history_stok_buku
    {
        public int id_histori_stok { get; set; }
        public string nama_buku { get; set; }
        public string penerbit_buku { get; set; }
        public int tambahan_stok_buku { get; set; }
    }
}
