//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabel_peminjam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tabel_peminjam()
        {
            this.tabel_peminjaman = new HashSet<tabel_peminjaman>();
        }
    
        public int id_peminjam { get; set; }
        public string nama_peminjam { get; set; }
        public string alamat_peminjam { get; set; }
        public string password_peminjam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tabel_peminjaman> tabel_peminjaman { get; set; }
    }
}
